### PR TITLE
PageIndex Generation Reverted

### PR DESCRIPTION
**Pull request by fcuneyt**
I added an option named "RevertIndex" to generate Index Page in ascending or descending order.

### CODE REVIEW

**Comment by uhaciogullari** [comment]
Can you revert the formatting changes? It would be easier to see what has actually changed.

**Comment by fcuneyt** [comment]
I reverted text format in homeController only added 2 parameters.

**Comment by uhaciogullari** [comment]
The formatting changes are still visible [here](https://github.com/uhaciogullari/SimpleMvcSitemap/pull/12/files)

**Comment by fcuneyt** [comment]
Changed rows are 43 and 51 only added last parameter "false".

**Pull request closed without merging**
